accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:post_pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:post_pk>/answer/<str:answer>/', views.answer, name='answer'),
    path('<int:post_pk>/likes/', views.likes, name='likes'),
    path('<int:post_pk>/comment/', views.comment_create, name='comment_create'),
    path('<int:post_pk>/comment/<int:comment_pk>/delete/',
         views.comment_delete, name='comment_delete'),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    followings = models.ManyToManyField(
        'self', symmetrical=False, related_name='followers')
    profile_img = models.ImageField(upload_to='profile/')

posts/models.py
from django.db import models
from django.conf import settings

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=80)
    select1_content = models.CharField(max_length=200)
    select2_content = models.CharField(max_length=200)
    image1 = models.ImageField(blank=True, upload_to='%Y/%m/%d/')
    image2 = models.ImageField(blank=True, upload_to='%Y/%m/%d/')
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    select1_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='select1_posts')
    select2_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='select2_posts')
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='like_posts')


class Comment(models.Model):
    content = models.CharField(max_length=200)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    post = models.ForeignKey(to=Post, on_delete=models.CASCADE)

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('username', 'email', 'password1', 'password2', 'profile_img',)
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control custom-input-form', }),
            'email': forms.TextInput(attrs={'class': 'form-control custom-input-form', }),
            'first_name': forms.TextInput(attrs={'class': 'form-control custom-input-form', }),
            'last_name': forms.TextInput(attrs={'class': 'form-control custom-input-form', }),
        }


class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(
        label='아이디',
        widget=forms.TextInput(attrs={'class': 'form-control', }),
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', }),
    )

    class Meta:
        model = get_user_model()
        fields = '__all__'

accounts/views.py
from django.shortcuts import render, redirect
from .models import User
from .forms import CustomUserCreationForm, CustomAuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model

# Create your views here.


def login(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('posts:index')
    else:
        form = CustomAuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('posts:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


@login_required
def logout(request):
    auth_logout(request)
    return redirect('posts:index')


@login_required
def profile(request, username):
    User = get_user_model()
    person = User.objects.get(username=username)
    context = {
        'person': person,
    }
    return render(request, 'accounts/profile.html', context)


@login_required
def follow(request, user_pk):
    User = get_user_model()
    person = User.objects.get(pk=user_pk)

    if request.user != person:
        if person.followers.filter(pk=request.user.pk).exists():
            person.followers.remove(request.user)

        else:
            person.followers.add(request.user)

    return redirect('accounts:profile', person.username)

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
<h4>로그인</h4>
<form action="{% url 'accounts:login' %}" method="post" class="custom-input-form">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit">
</form>

{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %} 
{% load static %}

{% block style %}
  <style>
    body {
      background-image: url("{% static 'back.jpg' %}");
      background-position: center;
      background-attachment: fixed;
      background-size: cover;
    }

    .body-size{
      {% comment %} border: black solid 1px; {% endcomment %}
      width: 500px;
      height: 460px;
      margin: 0 auto;
      background-color: white;
      border-radius: 12px;
      box-shadow: 8px 7px 30px -8px rgba(0,0,0,0.45);
    }
    
    .information-size{
      height: 230px;
    }

    .number {
      font-size: 2rem;
      font-weight: 500;
      padding-top: 1em;
    }

    .posts {
      text-decoration-line: none;
      color: black;
    }
    .posts:hover {
      font-weight: bold;
      text-decoration-line: underline;
    }

  </style>
{% endblock style %}

{% block content %}
<div class="body-size">
  <!-- header 시작 -->
  <div class="d-flex justify-content-between align-items-center m-3">
    <div class="d-flex justify-content-between align-items-center">
      <h1 class="m-0 me-1">{{ person.username }}</h1>
      <div>
        {% if request.user.is_authenticated %}
          {% if request.user != person %}
            {% if request.user in person.followers.all %}
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-patch-check-fill" viewBox="0 0 16 16">
                <path d="M10.067.87a2.89 2.89 0 0 0-4.134 0l-.622.638-.89-.011a2.89 2.89 0 0 0-2.924 2.924l.01.89-.636.622a2.89 2.89 0 0 0 0 4.134l.637.622-.011.89a2.89 2.89 0 0 0 2.924 2.924l.89-.01.622.636a2.89 2.89 0 0 0 4.134 0l.622-.637.89.011a2.89 2.89 0 0 0 2.924-2.924l-.01-.89.636-.622a2.89 2.89 0 0 0 0-4.134l-.637-.622.011-.89a2.89 2.89 0 0 0-2.924-2.924l-.89.01-.622-.636zm.287 5.984-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7 8.793l2.646-2.647a.5.5 0 0 1 .708.708z"/>
              </svg>
            {% else %}
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-patch-check" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M10.354 6.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7 8.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
                <path d="m10.273 2.513-.921-.944.715-.698.622.637.89-.011a2.89 2.89 0 0 1 2.924 2.924l-.01.89.636.622a2.89 2.89 0 0 1 0 4.134l-.637.622.011.89a2.89 2.89 0 0 1-2.924 2.924l-.89-.01-.622.636a2.89 2.89 0 0 1-4.134 0l-.622-.637-.89.011a2.89 2.89 0 0 1-2.924-2.924l.01-.89-.636-.622a2.89 2.89 0 0 1 0-4.134l.637-.622-.011-.89a2.89 2.89 0 0 1 2.924-2.924l.89.01.622-.636a2.89 2.89 0 0 1 4.134 0l-.715.698a1.89 1.89 0 0 0-2.704 0l-.92.944-1.32-.016a1.89 1.89 0 0 0-1.911 1.912l.016 1.318-.944.921a1.89 1.89 0 0 0 0 2.704l.944.92-.016 1.32a1.89 1.89 0 0 0 1.912 1.911l1.318-.016.921.944a1.89 1.89 0 0 0 2.704 0l.92-.944 1.32.016a1.89 1.89 0 0 0 1.911-1.912l-.016-1.318.944-.921a1.89 1.89 0 0 0 0-2.704l-.944-.92.016-1.32a1.89 1.89 0 0 0-1.912-1.911l-1.318.016z"/>
              </svg>
            {% endif %}
          {% else %}
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
            <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
            <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
          </svg>
        {% endif %}
      {% endif %}
      </div>
    </div>
    <div>
      {% if request.user.is_authenticated %}
        {% if request.user != person %}
          <form action="{% url 'accounts:follow' person.pk %}" method="post">
            {% csrf_token %} 
            {% if request.user in person.followers.all %}
              <input class="btn btn-sm btn-outline-dark" type="submit" value="언팔로우"/>
            {% else %}
              <input class="btn btn-sm btn-outline-dark" type="submit" value="팔로우"/>
            {% endif %}
          </form>
        {% endif %}
      {% else %}
        <input class="btn btn-sm btn-outline-dark" type="button" value="팔로우" disabled/>
      {% endif %}
    </div>
  </div>
  <!-- header 끝 -->

  <!-- information 시작 -->
  <div class="container information-size text-center border">
    <div class="row h-75 py-2">
      <div class="col-4 pe-0">
        <div class="h-100">
          <img class="w-100 h-100 rounded-circle" style="object-fit: cover;" src="{{person.profile_img.url}}" alt="img" >
        </div>
      </div>
      <div class="col-8 d-flex">
        <div class="col">
          <div class="number h-75">{{ person.post_set.all|length }}</div>
          <div class="h-25">Posts</div>
        </div>
        <div class="col">
          <div class="number h-75">{{ person.followers.all|length }}</div>
          <div class="h-25">Followers</div>
        </div>  
        <div class="col">
          <div class="number h-75">{{ person.followings.all|length }}</div>
          <div class="h-25">Following</div>
        </div>
      </div>
    </div>
    <div class="row h-25 pt-3">
      <div class="col text-start">
        email : {{ person.email }}
      </div>
    </div>
  </div>
  <!-- information 끝 -->

  <!-- contents 시작 -->
  <div>
    <div class="accordion accordion-flush" id="accordionFlushExample">
      <div class="accordion-item">
        <h2 class="accordion-header">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
            작성한 게시글
          </button>
        </h2>
        <div id="flush-collapseOne" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample">
          <div class="accordion-body">
            {% for post in person.post_set.all %}
            <div class="posts">
              <a class="posts" href="{% url 'posts:detail' post.pk %}">{{ post.title }}</a>
            </div>
            {% endfor %}
          </div>
        </div>
        <div class="accordion-item">
          <h2 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
              좋아요한 게시글
            </button>
          </h2>
          <div id="flush-collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample">
            <div class="accordion-body">
              {% for like_post in person.like_posts.all %}
              <div class="posts">
                <a class="posts" href="{% url 'posts:detail' like_post.pk %}">{{ like_post.title }}</a>
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
        <div class="accordion-item">
          <h2 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseThree" aria-expanded="false" aria-controls="flush-collapseThree">
              작성한 댓글
            </button>
          </h2>
          <div id="flush-collapseThree" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample">
            <div class="accordion-body">
              {% for comment in person.comment_set.all %}
              <div>
                <a class="posts" href="{% url 'posts:detail' comment.post.pk %}">{{ comment.content }}</a>
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div> 
  </div>
  <!-- contents 끌 -->
  
</div>  
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}
<h4>회원가입</h4>
<form action="{% url 'accounts:signup' %}" method="post" enctype="multipart/form-data" class="custom-input-form">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit">
</form>

{% endblock content %}