accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:post_pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:post_pk>/answer/<str:answer>/', views.answer, name='answer'),
    path('<int:post_pk>/likes/', views.likes, name='likes'),
    path('<int:post_pk>/comment/', views.comment_create, name='comment_create'),
    path('<int:post_pk>/comment/<int:comment_pk>/delete/',
         views.comment_delete, name='comment_delete'),

]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Balance game</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'style.css' %}">
    {% block style %}{% endblock style %}
  </head>
  <body>
    <div class="container-sm">
      {# Navigation Bar #} {% include 'navbar.html' %}

      <main>
        {% block content %}{% endblock content %}
      </main>
    </div>

{% block script %}{% endblock script %}

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/navbar.html
<nav
  class="navbar navbar-expand-lg bg-body-tertiary sticky-top rounded-bottom-3 shadow-sm ps-2"
>
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'posts:index' %}">Balance Game</a>

    <div class="d-flex" id="navbarSupportedContent">
      {% if request.user.is_authenticated %}
      <span class="navbar-text me-5 align-self-center">
        <b>{{ request.user }}</b>
        님, 안녕하세요!
      </span>
      {% endif %}
      <ul class="navbar-nav ms-auto me-3 mb-2 mb-lg-0 d-flex flex-row">
        {% if request.user.is_authenticated %}
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle fw-bold"
            href="#"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            {{ request.user }}
          </a>
          <ul
            class="dropdown-menu"
            style="position: absolute; left: auto; right: 0"
          >
            <li class="">
              <a
                class="dropdown-item ps-1 d-flex justify-content-center align-items-center"
                href="{% url 'accounts:profile' user.username %}"
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="currentColor"
                  class="bi bi-person-fill custom-profile-icon"
                  viewBox="0 0 16 16"
                >
                  <path
                    d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3Zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z"
                  />
                </svg>
                <span>프로필</span>
              </a>
            </li>

            <li><hr class="dropdown-divider" /></li>
            <li>
              <form action="{% url 'accounts:logout' %}" method="post" class="">
                {% csrf_token %}
                <button
                  type="submit"
                  class="bg-transparent border-0 p-0 w-100 text-start"
                >
                  <a class="dropdown-item">로그아웃</a>
                </button>
              </form>
            </li>
          </ul>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link me-3" href="{% url 'accounts:login' %}">로그인</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>