accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:post_pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:post_pk>/answer/<str:answer>/', views.answer, name='answer'),
    path('<int:post_pk>/likes/', views.likes, name='likes'),
    path('<int:post_pk>/comment/', views.comment_create, name='comment_create'),
    path('<int:post_pk>/comment/<int:comment_pk>/delete/',
         views.comment_delete, name='comment_delete'),

]

posts/models.py
from django.db import models
from django.conf import settings

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=80)
    select1_content = models.CharField(max_length=200)
    select2_content = models.CharField(max_length=200)
    image1 = models.ImageField(blank=True, upload_to='%Y/%m/%d/')
    image2 = models.ImageField(blank=True, upload_to='%Y/%m/%d/')
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    select1_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='select1_posts')
    select2_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='select2_posts')
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='like_posts')


class Comment(models.Model):
    content = models.CharField(max_length=200)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    post = models.ForeignKey(to=Post, on_delete=models.CASCADE)

posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'select1_content',
                  'select2_content', 'image1', 'image2')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', }),
            'select1_content': forms.Textarea(attrs={'class': 'form-control', 'rows': '2', }),
            'select2_content': forms.Textarea(attrs={'class': 'form-control', 'rows': '2', }),

        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)
        labels = {
            'content': '댓글',
        }
        widgets = {
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': '2', })
        }

posts/views.py
from django.shortcuts import render, redirect
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
# Create your views here.


def index(request):
    posts = Post.objects.all().order_by('pk')
    post_last = posts.last()
    context = {
        'posts': posts,
        'post_last': post_last,
    }
    return render(request, 'posts/index.html', context)


def detail(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    comments = post.comment_set.all()
    comment_form = CommentForm()
    context = {
        'post': post,
        'comments': comments,
        'comment_form': comment_form,
    }
    return render(request, 'posts/detail.html', context)


@login_required
def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('posts:detail', post_pk=post.pk)

    else:
        form = PostForm()

    context = {
        'form': form,
    }
    return render(request, 'posts/create.html', context)


def answer(request, post_pk, answer):

    post = Post.objects.get(pk=post_pk)
    if request.user not in post.select1_users.all() and request.user not in post.select2_users.all():
        answer1 = request.POST.get('select1')
        answer2 = request.POST.get('select2')

        if answer1 == post.select1_content:
            post.select1_users.add(request.user)
        else:
            post.select2_users.add(request.user)

    return redirect('posts:detail', post.pk)


@login_required
def likes(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    if request.user in post.like_users.all():
        post.like_users.remove(request.user)
        is_liked = False
    else:
        post.like_users.add(request.user)
        is_liked = True
    context = {
        'is_liked': is_liked,
        'like_count': post.like_users.count(),
    }

    return JsonResponse(context)
    return redirect('posts:detail', post.pk)


@login_required
def comment_create(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.user = request.user
        comment.post = post
        comment.save()

    return redirect('posts:detail', post.pk)


@login_required
def comment_delete(request, post_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.user == comment.user:
        comment.delete()

    return redirect('posts:detail', post_pk)

posts/templates/posts/create.html
{% extends 'base.html' %} {% block content %}
{% load static %}
<h1>CREATE</h1>

<form action="{% url 'posts:create' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %} {{form.as_p}}
  <a href="https://unsplash.com/">이미지 검색<img src="{% static 'Unsplash_Logo_Full_Stacked.png' %}" alt="" style="width: 40px;" class="mx-3"></a>
  <input type="submit" class="btn btn-outline-dark" />
</form>

{% endblock content %}

posts/templates/posts/detail.html
{% extends 'base.html' %} {% block content %}
{% load static %}

<div class="mt-5"><h4 class="text-center"><b>{{post.title}}</b></h4>
<h6 class="d-flex justify-content-end">
  <p>작성자: </p>
  <a class="mx-2" href="{% url 'accounts:profile' post.user.username %}">{{post.user}}</a>
</h6></div>


<div class="row">
  <div class="card object-fit-cover col-5 text-center my-2 shadow p-3 mb-5 bg-body-tertiary rounded border-light" style="width:41%">
    <form
          action="{% url 'posts:answer' post.pk post.select1_content %}"
          method="POST"
     >
      {% csrf_token %}  
      <button class="my-2 btn btn-light" type="submit" name="select1" value="{{post.select1_content}}"/>

        {% if post.image1 %}
          <img class="card-img-top"  src="{{post.image1.url}}" alt="img" />
        {% else %}
        <img class="object-fit-cover custom-crsl-img-size rounded" src="{% static '1.jpg' %}" alt="">
        {% endif %}
      
        <div class="card-body">
          {{ post.select1_content}} : {{ post.select1_users.all|length }}
        </div>    

      </button>
    </form>
  </div>    
  

  <div class="col-2 d-flex text-center justify-content-center align-items-center">
      <h4><b>VS</b></h4>
  </div>


  
  <div class="card col-5 text-center my-2 shadow p-3 mb-5 bg-body-tertiary rounded border-light" style="width:41%">
    <form
    action="{% url 'posts:answer' post.pk post.select2_content %}"
    method="post"
    >
      {% csrf_token %}
      <button class="col my-2 btn btn-light" type="submit" name="select2" value="{{post.select2_content}}"/>
          {% if post.image2 %}
            <img class="card-img-top"  src="{{post.image2.url}}" alt="img" />
          {% else %}
          <img class="object-fit-cover custom-crsl-img-size rounded" src="{% static '2.jpg' %}" alt="">
          {% endif %}
      
        <div class="card-body">

          {{ post.select2_content }} : {{ post.select2_users.all|length }}
        </div>
      
      </button>
    </form>

  </div>
        
</div>

<div class="d-flex d-inline-block justify-content-end mt-2">
  <form id="like-form" data-post-id="{{post.pk}}">
    {% csrf_token %} {% if request.user in post.like_users.all %}
    <input
      class="btn btn-sm btn-outline-dark"
      type="submit"
      value="좋아요 취소"

    > 
 
    {% else %}
    <input class="btn btn-sm btn-outline-danger" type="submit" value="좋아요" />
  
    {% endif %}

  </form>
  <div class="mt-1 ms-1 small d-flex justify-content-center align-content-center" id="like-count">{{ post.like_users.all|length }}</div>

  <a class="btn btn-sm btn-outline-info mx-2" href="{% url 'posts:index' %}"
  >뒤로가기</a
>


</div>


{# comment #}
<hr class="mt-2">
<form action="{% url 'posts:comment_create' post.pk %}" method="post">
  {% csrf_token %} {{ comment_form.as_p }}
  <button type="submit" class="btn btn-sm btn-outline-success d-flex justify-content-end">제출</button>
</form>

<hr>
{% for comment in comments %}
<p>글쓴이: {{ comment.user }}</p>
<p>댓글 내용: {{ comment.content }}</p>


{% if request.user == comment.user %}
<form action="{% url 'posts:comment_delete' post.pk comment.pk %}" method="post">

  {% csrf_token %}
  <button type="submit" class="btn btn-sm btn-outline-danger py-1 px-2">삭제</button>
</form>
{% endif %}

<hr />
{% endfor %} 

{% endblock content %}

{% block script %}

<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>

  {% comment %} document.querySelector('.card').addEventListener('mouseenter',  function (event) {
    event.target.style.border = "white";
    console.log(event.target.style.border)
  }, false) {% endcomment %}


  const form = document.querySelector('#like-form')
  const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value

  form.addEventListener('submit', function (event) {
    // 이벤트 기본 동작 취소
    event.preventDefault()
    
    // likes url을 위해 html에서 post.pk값 가져옴  
    const postId = event.target.dataset.postId

    // axios로 요청 보내기
    axios ({
      method : 'post',
      url : `/posts/${postId}/likes/`,
      headers: {'X-CSRFToken': csrftoken},

    })
    .then((response) => {
      // console.log(response.data.is_liked)
      const isLiked = response.data.is_liked
      const likeBtn = document.querySelector('#like-form > input[type=submit]')
      if (isLiked === true) {

        // 버튼 조작
        likeBtn.value = '좋아요 취소'

      } else{
        likeBtn.value = '좋아요'

      }

      // 좋아요 수 DOM 조작
      const likeCountTag = document.querySelector('#like-count')

      const likeCountData = response.data.like_count

      // 선택한 span 태그의 내용을 좋아요 수 데이터로 채워넣기
      likeCountTag.textContent = likeCountData
    })
  })
</script>

{% endblock script %}

posts/templates/posts/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


{% if posts %}
<div class="row text-center mt-3">
  <div class="col-1"></div>
  <div class="col-10">
    <div id="carouselAuto" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <a href="{% url 'posts:detail' post_last.pk %}">
            {% if post_last.image1 %}
              <img class="d-block w-100 object-fit-cover custom-crsl-img-size rounded" src="{{ post_last.image1.url }}" alt="post image1">
              {% else %}
              <img class="d-block w-100 object-fit-cover custom-crsl-img-size rounded" src="{% static 'posts/default_one.jpg' %}" alt="post image1 default">
            </a>
            {% endif %}
        <div class="carousel-caption d-none d-sm-block caption-with-bg-color">
          <h2>{{ post_last.title }}</h2>
          <h5 class="fw-light">{{ post_last.select1_content }}</h5>
        </div>
      </div>
          
      <div class="carousel-item">
        <a href="{% url 'posts:detail' post_last.pk %}">
          {% if post_last.image2 %}
            <img class="d-block w-100 object-fit-cover custom-crsl-img-size rounded" src="{{ post_last.image2.url }}" alt="post image2">
          {% else %}
            <img class="d-block w-100 object-fit-cover custom-crsl-img-size rounded" src="{% static 'posts/default_two.jpg' %}" alt="post image1 default">
          {% endif %}
        </a>
        <div class="carousel-caption d-none d-sm-block caption-with-bg-color">
          <h2>{{ post_last.title }}</h2>
          <h5 class="fw-light">{{ post_last.select2_content }}</h5>
        </div>
      </div>

          {% comment %} 마지막 게시글 제외하고 반복 {% endcomment %}
      {% for post in posts|slice:"1:" %}
        <div class="carousel-item">
          <a href="{% url 'posts:detail' post.pk %}">
            {% if post.image1 %}
              <img class="d-block w-100 object-fit-cover custom-crsl-img-size rounded" src="{{ post.image1.url }}" alt="post image1">
            {% else %}
              <img class="d-block w-100 object-fit-cover custom-crsl-img-size rounded" src="{% static 'posts/default_one.jpg' %}" alt="post image1 default">
            {% endif %}
          </a>
          <div class="carousel-caption d-none d-sm-block caption-with-bg-color">
            <h2>{{ post.title }}</h2>
            <h5 class="fw-light">{{ post.select1_content }}</h5>
          </div>
        </div>
          
        <div class="carousel-item">
          <a href="{% url 'posts:detail' post.pk %}">
            {% if post.image2 %}
              <img class="d-block w-100 object-fit-cover custom-crsl-img-size rounded" src="{{ post.image2.url }}" alt="post image2">
            {% else %}
              <img class="d-block w-100 object-fit-cover custom-crsl-img-size rounded" src="{% static 'posts/default_two.jpg' %}" alt="post image1 default">
            {% endif %}
          </a>
          <div class="carousel-caption d-none d-sm-block caption-with-bg-color">
            <h2>{{ post.title }}</h2>
            <h5 class="fw-light">{{ post.select2_content }}</h5>
          </div>
        </div>
      {% endfor %}
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselAuto" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselAuto" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
    </div>
  </div>
</div>
{% endif %}
{% comment %} 여기부터 리스트 {% endcomment %}
<div class="row mt-2">
  <div class="col-1"></div>
  <div class="col-10">
    <ol class="list-group list-group-numbered">
      {% for post in posts %}
        <li class="list-group-item d-flex justify-content-between align-items-end">
          <div class="ms-2 me-auto">
            <div class="fw-bold">
              <a href="{% url 'posts:detail' post.pk %}">
                {{ post.title }}
              </a>
            </div>
            {{ post.select1_content }} vs {{ post.select2_content }}
          </div>
          <span class="badge bg-dark-subtle rounded-pill">
            {{ post.select1_users.all|length }}
          </span><span class="text-secondary">:</span>
          <span class="badge bg-dark-subtle rounded-pill">{{ post.select2_users.all|length }}</span>
        </li>
      {% endfor %}
      </ol>
  </div>
  <div class="col-1"></div>
</div>
<div class="row">
  <div class="col-1"></div>
  <div class="col-10 text-end mt-3">
    <a class="btn btn-sm btn-outline-warning" href="{% url 'posts:create' %}">생성하기</a>
  </div>
</div>



{% endblock content %}